### PR TITLE
WIP: sac版本更新至102

### PR DESCRIPTION
**Pull request by wangliang1989**

### CODE REVIEW

**Comment by core-man** [comment]
Do we really want to update sac to 102? I think SAC101.6 is enough and we should use ObsPy first in the future.

**Comment by wangliang1989** [comment]
> Do we really want to update sac to 102? I think SAC101.6 is enough and we should use ObsPy first in the future.

Yes, We do

**Comment by wangliang1989** [comment]
> Do we really want to update sac to 102? I think SAC101.6 is enough and we should use ObsPy first in the future.

sac的静态库是很多程序的依赖

**Comment by seisman** [comment]
与 SAC 102 无关的修改，不要提交到 102 分支。

目前的计划是，master分支依然是SAC 101.6a，102分支是 SAC 102。等到102分支足够成熟之后，会发布v4.2版本，然后把102分支的内容合并到 master 分支。

**Pull request closed without merging**
