### PR TITLE
Move how-to-read into SAC introduction

### PR DESCRIPTION
**Pull request by core-man**
Related to #160.

### CODE REVIEW

**Comment by seisman** [comment]
Perhaps also rename this file?

**Comment by core-man** [comment]
> Perhaps also rename this file?

read-docs?

**Comment by seisman** [comment]
> > Perhaps also rename this file?
> 
> read-docs?

reading-guides?

**Review by seisman — APPROVED** [review]

**Comment by core-man** [comment]
> > > Perhaps also rename this file?
> > 
> > 
> > read-docs?
> 
> reading-guides?

done in 6428b5c.

the title is now `文档阅读指南`.

**Pull request merged**
